name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACC_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker us-docker.pkg.dev 

      - name: Build and Push Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gridstream-api \
            --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --no-allow-unauthenticated \
            --set-env-vars GO_ENV=production \
            --set-env-vars PORT=8080 \
            --set-env-vars OUTPUT=stdout \
            --set-env-vars LEVEL=INFO \
            --set-env-vars FORMAT=JSON \
            --set-env-vars FIREBASE_GOOGLE_CREDENTIAL=${{ secrets.FIREBASE_GOOGLE_CREDENTIAL }} \
            --set-env-vars CREDS_PATH=${{ secrets.CREDS_PATH }} \
            --set-env-vars FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            --set-env-vars ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
            --set-secrets=${{ secrets.FIREBASE_GOOGLE_CREDENTIAL }}=FIREBASE_GOOGLE_CREDENTIAL:1 \
            --set-secrets=${{ secrets.CREDS_PATH }}=CREDS_PATH:1