name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACC_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api

      - name: Create env.yaml
        run: |
          cat > env.yaml << EOF
          GO_ENV: "production"
          PORT: "8080"
          OUTPUT: "stdout"
          LEVEL: "INFO"
          FORMAT: "JSON"
          FIREBASE_GOOGLE_CREDENTIAL: "${{ secrets.FIREBASE_GOOGLE_CREDENTIAL }}"
          CREDS_PATH: "${{ secrets.CREDS_PATH }}"
          FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
          ALLOWED_ORIGINS: "${{ secrets.ALLOWED_ORIGINS }}"
          EOF

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gridstream-api \
            --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gridstream/api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --no-allow-unauthenticated \
            --env-vars-file env.yaml \
            --set-secrets=${{ secrets.CREDS_PATH }}=CREDS_PATH:1,${{ secrets.FIREBASE_GOOGLE_CREDENTIAL }}=FIREBASE_GOOGLE_CREDENTIAL:1
